### ISSUE TITLE
Crash with AE rv3, Logistics Pipes

### ISSUE THREAD

**Issue by KageDragon** [ternsip/Placemod#4]
PlaceMod crashes with Applied Energistics rv3 (But not rv2)

[Crash log](http://pastebin.com/3BCtzVtN)

And the relevant bit of code from AE: [Link](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/91b8d30a15bf098257deee70d9e36888948b6f42/src/main/java/appeng/items/parts/ItemMultiPart.java)

```java
public IIcon getIconFromDamage( int dmg )
	{
		final PartTypeWithVariant registeredType = this.registered.get( dmg );
		if( registeredType != null )
		{
			return registeredType.ico;
		}

		final String formattedRegistered = Arrays.toString( this.registered.keySet().toArray() );
		throw new MissingDefinition( "Tried to get the icon from a non-existent part with damage value " + dmg + ". There were registered: " + formattedRegistered + '.' );
	}
```

Update: It seems Logistics Pipes causes this too...

**Comment by ternsip** [comment]
Fixed.
Download new 3.7 version.

**Comment by KageDragon** [comment]
Confirmed working
