### ISSUE TITLE
[1.10.2] ALLOWED_DIMENSIONS Ignored

### ISSUE THREAD

**Issue by kerenon** [ternsip/Placemod#5]
It seems the config option `ALLOWED_DIMENSIONS=-1, 0, 1` is ignored. I have checked AbyssalCraft and RFTools dimensions, and every single one of them has random schematics inserted.

**Comment by ternsip** [comment]
Can you put your ALLOWED_DIMENSIONS list for RFTools and AbyssalCraft here?

**Comment by ternsip** [comment]
Oh lord, yes, need to fix it. wait 3.8 version

**Comment by ternsip** [comment]
https://github.com/ternsip/Placemod/commit/119692fe1d75e9c7ed9b29ac736044d71eb6e5fa
Done

**Comment by kerenon** [comment]
Perfect :)
Thanks for the quick fix
